name: Unit Test PR

on:
  pull_request:
    branches-ignore:
      - master

env:
  SOLUTION_FOLDER: 'src/Schlechtums.Core'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Unit Test PR
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Nuget Packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1

      - name: Build Solution
        run: cd ${{ env.SOLUTION_FOLDER }}; dotnet build -nologo -c Release

      - name: Unit Test
        run: cd ${{ env.SOLUTION_FOLDER }}; dotnet test -nologo -c Release