name: Unit Test

on:
  push:
    branches-ignore:
      - master
      - dev
      - develop

env:
  SOLUTION_FOLDER: 'src/Schlechtums.Core'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Unit Test Commit
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1

      - name: Build Solution
        run: cd ${{ env.SOLUTION_FOLDER }}; dotnet build -nologo -c Release

      - name: Unit Test
        run: cd ${{ env.SOLUTION_FOLDER }}; dotnet test -nologo -c Release

  SonarQube:
    runs-on: ubuntu-latest
    name: SonarQube Analyze
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Cache Nuget Packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Install SonarQube scanner
        shell: pwsh
        run: dotnet tool update dotnet-sonarscanner --global

      - name: Install coverlet.console
        shell: pwsh
        run: |
          dotnet tool install coverlet.console --global

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: |
          cd ${{ env.SOLUTION_FOLDER }}
          dotnet-sonarscanner begin /d:sonar.cs.opencover.reportsPaths=coverage.opencover.xml /k:"schlechtums_Core" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}"
          dotnet build
          coverlet Schlechtums.Core.UnitTest/bin/Debug/netcoreapp3.1/Schlechtums.Core.UnitTest.dll --target "dotnet" --targetargs "test --no-build" --format opencover
          dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
